#! /bin/sh
# /etc/init.d/webcam

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting ROSV Control"
    ROSV_Control
    ;;
  stop)
    echo "Stopping ROSV Control"
    killall ROSV_Control
    ;;
  *)
    echo "Usage: /etc/init.d/ROSV_Control_Init {start|stop}"
    exit 1
    ;;
esac

exit 0
